In [1]:
import pandas as pd
import numpy as np

In [9]:



for generator_name in ['Molpher', 'DrugEx_GT_epsilon_0.1','DrugEx_GT_epsilon_0.6', 'DrugEx_RNN_epsilon_0.1','DrugEx_RNN_epsilon_0.6', 'addcarbon']:
    for type_split in ['dis', 'sim']:
        for type_scaffold in ['csk']:
            def_gen_1 = []
            for x in [0,1,2,3,4]:    
                df_KL= pd.read_csv(f"cluster/median_OS_IS/results_median_only/{generator_name}/high_TC_OS_IS_{type_scaffold}_{generator_name}_{type_split}_{x}.csv")
                
                median = np.median(df_KL)
                def_gen_1.append(median)
                
                
            a = np.median(def_gen_1)
            
            
            def_gen_1.append(a)

            
            display(def_gen_1)
                
            df_gen = pd.read_csv(f"data/results/Glucocorticoid_receptor/{type_scaffold}_scaffolds/{type_split}/{generator_name}/df_all_clusters_with_mean.csv")
            df_gen['median_OS_IS'] = def_gen_1

            display(df_gen)
            mean = pd.DataFrame()
            mean = df_gen.loc[5].to_frame().T
            df_gen.to_csv(f"data/results/Glucocorticoid_receptor/{type_scaffold}_scaffolds/{type_split}/{generator_name}/df_all_clusters_with_med_with_mean.csv", index=False)
            mean.to_csv(f"data/results/Glucocorticoid_receptor/{type_scaffold}_scaffolds/{type_split}/{generator_name}_mean_with_med_{type_scaffold}_{type_split}.csv", index=False) #float_format='%.7f'

[0.6415094339622641,
 0.6481481481481481,
 0.6666666666666666,
 0.6346153846153846,
 0.5957446808510638,
 0.6415094339622641]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,Molpher_0,dis,csk,104715.0,916546.0,15/40,0.375000,0.114250,0.003302,0.000143,3016.0,0.641509
1,Molpher_1,dis,csk,119055.0,1070030.0,15/23,0.652174,0.111263,0.001107,0.000126,1183.0,0.648148
2,Molpher_2,dis,csk,105240.0,906891.0,9/40,0.225000,0.116045,0.000114,0.000086,103.0,0.666667
3,Molpher_3,dis,csk,89696.0,693460.0,20/37,0.540540,0.129346,0.006771,0.000223,4664.0,0.634615
4,Molpher_4,dis,csk,81634.0,532962.0,34/43,0.790698,0.153170,0.011847,0.000417,6240.0,0.595745
5,Molpher_mean,dis,csk,100068.0,823977.8,-,0.516682,0.124815,0.004628,0.000199,3041.2,0.641509

[0.6338028169014085,
 0.6333333333333333,
 0.6346153846153846,
 0.6388888888888888,
 0.64,
 0.6346153846153846]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,Molpher_0,sim,csk,109136.0,855964.0,29/38,0.763158,0.127501,0.014587,0.000266,12306.0,0.633803
1,Molpher_1,sim,csk,102110.0,818233.0,28/38,0.736842,0.124793,0.021406,0.000274,17148.0,0.633333
2,Molpher_2,sim,csk,101071.0,804684.0,23/37,0.621622,0.125603,0.013337,0.000228,10591.0,0.634615
3,Molpher_3,sim,csk,98457.0,801639.0,26/35,0.742857,0.122820,0.012606,0.000264,9980.0,0.638889
4,Molpher_4,sim,csk,108264.0,901697.0,22/35,0.628571,0.120067,0.004200,0.000203,3771.0,0.640000
5,Molpher_mean,sim,csk,103807.6,836443.4,-,0.698610,0.124157,0.013227,0.000247,10759.2,0.634615

[0.5217391304347826,
 0.5507246376811594,
 0.559322033898305,
 0.5714285714285714,
 0.6060606060606061,
 0.559322033898305]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_GT_epsilon_0.1_0,dis,csk,145495.0,781031.0,22/40,0.550000,0.186286,0.006871,0.000151,5330.0,0.521739
1,DrugEx_GT_epsilon_0.1_1,dis,csk,112956.0,791578.0,15/23,0.652174,0.142697,0.000613,0.000133,485.0,0.550725
2,DrugEx_GT_epsilon_0.1_2,dis,csk,135635.0,797694.0,11/40,0.275000,0.170034,0.000202,0.000081,161.0,0.559322
3,DrugEx_GT_epsilon_0.1_3,dis,csk,124771.0,812047.0,17/37,0.459460,0.153650,0.005656,0.000136,4567.0,0.571429
4,DrugEx_GT_epsilon_0.1_4,dis,csk,183283.0,863816.0,34/43,0.790698,0.212178,0.011443,0.000186,9773.0,0.606061
5,DrugEx_GT_epsilon_0.1_mean,dis,csk,140428.0,809233.2,-,0.545466,0.172969,0.004957,0.000137,4063.2,0.559322

[0.5172413793103449,
 0.5555555555555556,
 0.5352112676056338,
 0.5614035087719298,
 0.5945945945945946,
 0.5555555555555556]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_GT_epsilon_0.1_0,sim,csk,159254.0,822485.0,26/38,0.684211,0.193625,0.008265,0.000163,6742.0,0.517241
1,DrugEx_GT_epsilon_0.1_1,sim,csk,113778.0,791168.0,26/38,0.684211,0.143810,0.044082,0.000229,33404.0,0.555556
2,DrugEx_GT_epsilon_0.1_2,sim,csk,116779.0,881455.0,16/37,0.432432,0.132484,0.002328,0.000137,2047.0,0.535211
3,DrugEx_GT_epsilon_0.1_3,sim,csk,142125.0,843014.0,31/35,0.885714,0.168592,0.015759,0.000218,13079.0,0.561404
4,DrugEx_GT_epsilon_0.1_4,sim,csk,151498.0,810360.0,13/35,0.371429,0.186951,0.000226,0.000086,183.0,0.594595
5,DrugEx_GT_epsilon_0.1_mean,sim,csk,136686.8,829696.4,-,0.611599,0.165093,0.014132,0.000167,11091.0,0.555556

[0.62,
 0.6181818181818182,
 0.6271186440677966,
 0.5873015873015873,
 0.5490196078431373,
 0.6181818181818182]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_GT_epsilon_0.6_0,dis,csk,252886.0,907696.0,29/40,0.725000,0.278602,0.007596,0.000115,6843.0,0.620000
1,DrugEx_GT_epsilon_0.6_1,dis,csk,251493.0,912123.0,17/23,0.739130,0.275723,0.004296,0.000068,3902.0,0.618182
2,DrugEx_GT_epsilon_0.6_2,dis,csk,244568.0,891157.0,17/40,0.425000,0.274439,0.000897,0.000069,799.0,0.627119
3,DrugEx_GT_epsilon_0.6_3,dis,csk,291620.0,914068.0,24/37,0.648649,0.319035,0.007999,0.000082,7254.0,0.587302
4,DrugEx_GT_epsilon_0.6_4,dis,csk,297673.0,912328.0,37/43,0.860465,0.326279,0.019140,0.000124,17134.0,0.549020
5,DrugEx_GT_epsilon_0.6_mean,dis,csk,267648.0,907474.4,-,0.679649,0.294816,0.007986,0.000092,7186.4,0.618182

[0.5571428571428572,
 0.5892857142857143,
 0.6046511627906976,
 0.6326530612244898,
 0.6111111111111112,
 0.6046511627906976]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_GT_epsilon_0.6_0,sim,csk,315586.0,903941.0,36/38,0.947368,0.349122,0.017539,0.000114,15581.0,0.557143
1,DrugEx_GT_epsilon_0.6_1,sim,csk,266852.0,914909.0,32/38,0.842105,0.291670,0.030214,0.000120,26832.0,0.589286
2,DrugEx_GT_epsilon_0.6_2,sim,csk,273723.0,927535.0,30/37,0.810811,0.295108,0.011669,0.000110,10699.0,0.604651
3,DrugEx_GT_epsilon_0.6_3,sim,csk,243530.0,890164.0,32/35,0.914286,0.273579,0.020246,0.000131,17665.0,0.632653
4,DrugEx_GT_epsilon_0.6_4,sim,csk,263535.0,912064.0,29/35,0.828571,0.288944,0.008464,0.000110,7655.0,0.611111
5,DrugEx_GT_epsilon_0.6_mean,sim,csk,272645.2,909722.6,-,0.868628,0.299685,0.017626,0.000117,15686.4,0.604651

[0.65,
 0.673469387755102,
 0.6842105263157895,
 0.7571428571428571,
 0.6111111111111112,
 0.673469387755102]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_RNN_epsilon_0.1_0,dis,csk,59829.0,816954.0,12/40,0.300000,0.073234,0.001820,0.000201,1484.0,0.650000
1,DrugEx_RNN_epsilon_0.1_1,dis,csk,68831.0,800534.0,9/23,0.391304,0.085981,0.002829,0.000131,2258.0,0.673469
2,DrugEx_RNN_epsilon_0.1_2,dis,csk,73945.0,827443.0,6/40,0.150000,0.089366,0.000027,0.000081,22.0,0.684211
3,DrugEx_RNN_epsilon_0.1_3,dis,csk,55848.0,768679.0,13/37,0.351351,0.072654,0.001471,0.000233,1129.0,0.757143
4,DrugEx_RNN_epsilon_0.1_4,dis,csk,101550.0,774574.0,32/43,0.744186,0.131104,0.019496,0.000315,14812.0,0.611111
5,DrugEx_RNN_epsilon_0.1_mean,dis,csk,72000.6,797636.8,-,0.387368,0.090468,0.005128,0.000192,3941.0,0.673469

[0.55,
 0.5675675675675675,
 0.6,
 0.5961538461538461,
 0.6721311475409836,
 0.5961538461538461]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_RNN_epsilon_0.1_0,sim,csk,83393.0,823559.0,21/38,0.552632,0.101259,0.022751,0.000252,18320.0,0.550000
1,DrugEx_RNN_epsilon_0.1_1,sim,csk,92999.0,842946.0,22/38,0.578947,0.110326,0.023908,0.000237,19683.0,0.567568
2,DrugEx_RNN_epsilon_0.1_2,sim,csk,57526.0,850165.0,10/37,0.270270,0.067665,0.032497,0.000174,26758.0,0.600000
3,DrugEx_RNN_epsilon_0.1_3,sim,csk,102276.0,903489.0,12/35,0.342857,0.113201,0.021629,0.000117,19128.0,0.596154
4,DrugEx_RNN_epsilon_0.1_4,sim,csk,81618.0,817897.0,16/35,0.457143,0.099790,0.002212,0.000196,1805.0,0.672131
5,DrugEx_RNN_epsilon_0.1_mean,sim,csk,83562.4,847611.2,-,0.440370,0.098448,0.020599,0.000195,17138.8,0.596154

[0.5932203389830508,
 0.5964912280701754,
 0.6176470588235294,
 0.5714285714285714,
 0.5,
 0.5932203389830508]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_RNN_epsilon_0.6_0,dis,csk,75791.0,886338.0,18/40,0.450000,0.085510,0.007402,0.000238,6512.0,0.593220
1,DrugEx_RNN_epsilon_0.6_1,dis,csk,68725.0,884332.0,17/23,0.739130,0.077714,0.002428,0.000247,2142.0,0.596491
2,DrugEx_RNN_epsilon_0.6_2,dis,csk,80797.0,899324.0,11/40,0.275000,0.089842,0.000443,0.000136,398.0,0.617647
3,DrugEx_RNN_epsilon_0.6_3,dis,csk,90765.0,881222.0,27/37,0.729730,0.102999,0.016767,0.000298,14532.0,0.571429
4,DrugEx_RNN_epsilon_0.6_4,dis,csk,119424.0,904111.0,39/43,0.906977,0.132090,0.064557,0.000327,54827.0,0.500000
5,DrugEx_RNN_epsilon_0.6_mean,dis,csk,87100.4,891065.4,-,0.620167,0.097631,0.018319,0.000249,15682.2,0.593220

[0.5862068965517241,
 0.6052631578947368,
 0.6206896551724138,
 0.5925925925925926,
 0.5777777777777777,
 0.5925925925925926]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,DrugEx_RNN_epsilon_0.6_0,sim,csk,107715.0,909447.0,33/38,0.868421,0.118440,0.018234,0.000307,16286.0,0.586207
1,DrugEx_RNN_epsilon_0.6_1,sim,csk,91550.0,881406.0,30/38,0.789474,0.103868,0.044200,0.000328,37309.0,0.605263
2,DrugEx_RNN_epsilon_0.6_2,sim,csk,79140.0,878345.0,31/37,0.837838,0.090101,0.038390,0.000392,32473.0,0.620690
3,DrugEx_RNN_epsilon_0.6_3,sim,csk,78164.0,904329.0,28/35,0.800000,0.086433,0.026333,0.000358,23203.0,0.592593
4,DrugEx_RNN_epsilon_0.6_4,sim,csk,88192.0,886045.0,29/35,0.828571,0.099534,0.004473,0.000329,3946.0,0.577778
5,DrugEx_RNN_epsilon_0.6_mean,sim,csk,88952.2,891914.4,-,0.824861,0.099675,0.026326,0.000343,22643.4,0.592593

[1.0, 1.0, 1.0, 1.0, 0.9615384615384616, 1.0]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,addcarbon_0,dis,csk,766.0,1000000.0,2/40,0.050000,0.000766,0.001793,0.002618,1790.0,1.000000
1,addcarbon_1,dis,csk,942.0,1000000.0,1/23,0.043478,0.000942,0.003562,0.001063,3549.0,1.000000
2,addcarbon_2,dis,csk,758.0,1000000.0,0/40,0.000000,0.000758,0.000000,0.000000,0.0,1.000000
3,addcarbon_3,dis,csk,887.0,1000000.0,1/37,0.027027,0.000887,0.000343,0.001129,343.0,1.000000
4,addcarbon_4,dis,csk,931.0,1000000.0,2/43,0.046512,0.000931,0.003465,0.002153,3453.0,0.961538
5,addcarbon_mean,dis,csk,856.8,1000000.0,-,0.033403,0.000857,0.001833,0.001392,1827.0,1.000000

[0.9836065573770492, 0.9827586206896552, 1.0, 1.0, 1.0, 1.0]

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,addcarbon_0,sim,csk,866.0,1000000.0,3/38,0.078947,0.000866,0.003108,0.003476,3098.0,0.983607
1,addcarbon_1,sim,csk,846.0,1000000.0,10/38,0.263158,0.000846,0.030109,0.011962,29229.0,0.982759
2,addcarbon_2,sim,csk,861.0,1000000.0,13/37,0.351351,0.000861,0.010321,0.015330,10216.0,1.000000
3,addcarbon_3,sim,csk,878.0,1000000.0,7/35,0.200000,0.000878,0.022763,0.008037,22256.0,1.000000
4,addcarbon_4,sim,csk,868.0,1000000.0,4/35,0.114286,0.000868,0.006411,0.004630,6370.0,1.000000
5,addcarbon_mean,sim,csk,863.8,1000000.0,-,0.201548,0.000864,0.014542,0.008687,14233.8,1.000000

In [28]:
mean

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,TUPOR_unique,TUPOR_1,TUPOR_2,SESY,ASER,CwASo,metric_1,metric_2,KL_OS_IS,KL_OS_RS
5,DrugEx_GT_epsilon_0.6_mean,dis,csk,267648.0,907474.4,-,0.679649,0.025317,0.000147,1.055034,0.294816,0.007886,7186.4,0.000092,0.007986,0.000751,0.025066

In [29]:
df_gen = pd.read_csv("data/results/Glucocorticoid_receptor/csk_scaffolds/dis/Molpher/df_all_clusters_with_mean.csv")
df_gen

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,TUPOR_unique,TUPOR_1,TUPOR_2,SESY,ASER,CwASo,metric_1,metric_2
0,Molpher_0,dis,csk,104715.0,916546.0,15/40,0.375000,0.035812,0.000074,0.192796,0.114250,0.003291,3016.0,0.000143,0.003302
1,Molpher_1,dis,csk,119055.0,1070030.0,15/23,0.652174,0.054779,0.000038,0.198760,0.111263,0.001106,1183.0,0.000126,0.001107
2,Molpher_2,dis,csk,105240.0,906891.0,9/40,0.225000,0.021380,0.000046,0.121412,0.116045,0.000114,103.0,0.000086,0.000114
3,Molpher_3,dis,csk,89696.0,693460.0,20/37,0.540540,0.060264,0.000179,0.432727,0.129346,0.006726,4664.0,0.000223,0.006771
4,Molpher_4,dis,csk,81634.0,532962.0,34/43,0.790698,0.096859,0.000451,0.856230,0.153170,0.011708,6240.0,0.000417,0.011847
5,Molpher_mean,dis,csk,100068.0,823977.8,-,0.516682,0.053819,0.000158,0.360385,0.124815,0.004589,3041.2,0.000199,0.004628

In [ ]:
df_gen['KL_OS_IS'] = ['

In [20]:
df_KL_dis_0 = pd.read_csv("data/KL_divergence/df_KL_dis_0")
df_KL_dis_0

                 generator  KL_OS_IS  KL_OS_RS
0                  Molpher  0.404182  2.661215
1                 REINVENT  0.758605  2.952111
2                DrugEx_GT  0.377742  2.712360
3    DrugEx_GT_epsilon_0.1  0.756354  2.989940
4    DrugEx_GT_epsilon_0.6  0.405051  2.723309
5               DrugEx_RNN  0.568176  2.759121
6   DrugEx_RNN_epsilon_0.1  0.703502  2.879325
7   DrugEx_RNN_epsilon_0.6  0.518094  2.713713
8      DrugEx_epsilon_0.01  1.064774  3.556772
9       DrugEx_epsilon_0.1  0.832583  3.064448
10      DrugEx_epsilon_0.2  0.409366  2.658248
11      DrugEx_epsilon_0.4  0.370993  2.712992
12      DrugEx_epsilon_0.6  0.324838  2.678195

In [16]:
def connect_mean_value(reeptor, scaffold_type, type_cluster, generators_name_list):
    path = f"data/results/{receptor}/{scaffold_type}_scaffolds/{type_cluster}/"
    link = {}
    for generator in generators_name_list:
        link[f'link_{generator}'] = f'{path}{generator}_mean_with_med_{scaffold_type}_{type_cluster}.csv'

    df = pd.DataFrame()
    for x,y in link.items():
        a = pd.read_csv(y)
        df = pd.concat([df, a], ignore_index=True)

    df = df.drop(columns = ['TUPOR_'])

    dff = df.copy()
    dff['SSo'] = dff['SSo'].apply(lambda x : "{:,}".format(x))
    dff['USo'] = dff['USo'].apply(lambda x : "{:,}".format(x))
    dff['CwASo'] = dff['CwASo'].apply(lambda x : "{:,}".format(x))

    
    dff.to_csv(f"{path}/mean_with_med_{scaffold_type}_{type_cluster}_with_coma.csv", index = False)
    df.to_csv(f"{path}/mean_with_med_{scaffold_type}_{type_cluster}.csv", index = False)
    dff.to_html(f"{path}/mean_with_med_{scaffold_type}_{type_cluster}.html", index = False)

    
    display(df[['name','type_cluster','scaffold','USo',	'SSo','TUPOR', 'SESY','ASER','ASR','CwASo','median_OS_IS']])
    return df

In [17]:
#type_cluster = 'dis' #options: 'dis'|'sim' 
#scaffold_type = 'csk' #options: 'csk'|'murcko'
#generators_name_list = [ 'Molpher', 'REINVENT'] #options: 'Molpher'|'DrugEx'
receptor = 'Glucocorticoid_receptor' #options: 'Glucocorticoid_receptor'|'Leukocyte_elastase'

generators_name_list= ['Molpher', 'DrugEx_GT_epsilon_0.1','DrugEx_GT_epsilon_0.6', 'DrugEx_RNN_epsilon_0.1','DrugEx_RNN_epsilon_0.6', 'addcarbon']
for type_cluster in ['dis', 'sim']:
    for scaffold_type in ['csk']:
        df = connect_mean_value(receptor, scaffold_type, type_cluster, generators_name_list)

,name,type_cluster,scaffold,USo,SSo,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,Molpher_mean,dis,csk,100068.0,823977.8,0.516682,0.124815,0.004628,0.000199,3041.2,0.641509
1,DrugEx_GT_epsilon_0.1_mean,dis,csk,140428.0,809233.2,0.545466,0.172969,0.004957,0.000137,4063.2,0.559322
2,DrugEx_GT_epsilon_0.6_mean,dis,csk,267648.0,907474.4,0.679649,0.294816,0.007986,0.000092,7186.4,0.618182
3,DrugEx_RNN_epsilon_0.1_mean,dis,csk,72000.6,797636.8,0.387368,0.090468,0.005128,0.000192,3941.0,0.673469
4,DrugEx_RNN_epsilon_0.6_mean,dis,csk,87100.4,891065.4,0.620167,0.097631,0.018319,0.000249,15682.2,0.593220
5,addcarbon_mean,dis,csk,856.8,1000000.0,0.033403,0.000857,0.001833,0.001392,1827.0,1.000000

,name,type_cluster,scaffold,USo,SSo,TUPOR,SESY,ASER,ASR,CwASo,median_OS_IS
0,Molpher_mean,sim,csk,103807.6,836443.4,0.698610,0.124157,0.013227,0.000247,10759.2,0.634615
1,DrugEx_GT_epsilon_0.1_mean,sim,csk,136686.8,829696.4,0.611599,0.165093,0.014132,0.000167,11091.0,0.555556
2,DrugEx_GT_epsilon_0.6_mean,sim,csk,272645.2,909722.6,0.868628,0.299685,0.017626,0.000117,15686.4,0.604651
3,DrugEx_RNN_epsilon_0.1_mean,sim,csk,83562.4,847611.2,0.440370,0.098448,0.020599,0.000195,17138.8,0.596154
4,DrugEx_RNN_epsilon_0.6_mean,sim,csk,88952.2,891914.4,0.824861,0.099675,0.026326,0.000343,22643.4,0.592593
5,addcarbon_mean,sim,csk,863.8,1000000.0,0.201548,0.000864,0.014542,0.008687,14233.8,1.000000