In [16]:
import pandas as pd
import numpy as np

In [18]:
df_KL_dis_0 = pd.read_csv("data/KL_divergence/df_KL_dis_0")


def_gen_1 = []
def_gen_2 = []
generator_name = 'Molpher'
for x in [0,1,2,3,4]:
    try:
        df_KL= pd.read_csv(f"data/KL_divergence/df_KL_dis_{x}")
        def_gen_1.append(df_KL[df_KL.generator == generator_name][['KL_OS_IS']].values.flatten()[0])
        def_gen_2.append(df_KL[df_KL.generator == generator_name][['KL_OS_RS']].values.flatten()[0])
    except:
        def_gen_1.append(0)
        def_gen_2.append(0)
a = np.mean(def_gen_1)
b = np.mean(def_gen_2)

def_gen_1.append(a)
def_gen_2.append(b)
    
df_gen = pd.read_csv(f"data/results/Glucocorticoid_receptor/csk_scaffolds/dis/{generator_name}/df_all_clusters_with_mean.csv")
df_gen['KL_OS_IS'] = def_gen_1
df_gen['KL_OS_RS'] = def_gen_2

In [19]:
df_gen

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,TUPOR_unique,TUPOR_1,TUPOR_2,SESY,ASER,CwASo,KL_OS_IS,KL_OS_RS
0,Molpher_0,dis,csk,104715.0,916546.0,15/40,0.375000,0.035812,0.000074,0.192796,0.114250,0.003291,3016.0,0.404182,2.661215
1,Molpher_1,dis,csk,119055.0,1070030.0,15/23,0.652174,0.054779,0.000038,0.198760,0.111263,0.001106,1183.0,0.000000,0.000000
2,Molpher_2,dis,csk,105240.0,906891.0,9/40,0.225000,0.021380,0.000046,0.121412,0.116045,0.000114,103.0,0.346091,3.236028
3,Molpher_3,dis,csk,89696.0,693460.0,20/37,0.540540,0.060264,0.000179,0.432727,0.129346,0.006726,4664.0,0.383733,2.368863
4,Molpher_4,dis,csk,81634.0,532962.0,34/43,0.790698,0.096859,0.000451,0.856230,0.153170,0.011708,6240.0,0.436527,2.200132
5,Molpher_mean,dis,csk,100068.0,823977.8,-,0.516682,0.053819,0.000158,0.360385,0.124815,0.004589,3041.2,0.314107,2.093248

In [3]:
df_gen = pd.read_csv("data/results/Glucocorticoid_receptor/csk_scaffolds/dis/Molpher/df_all_clusters_with_mean.csv")
df_gen

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,TUPOR_unique,TUPOR_1,TUPOR_2,SESY,ASER,CwASo
0,Molpher_0,dis,csk,104715.0,916546.0,15/40,0.375000,0.035812,0.000074,0.192796,0.114250,0.003291,3016.0
1,Molpher_1,dis,csk,119055.0,1070030.0,15/23,0.652174,0.054779,0.000038,0.198760,0.111263,0.001106,1183.0
2,Molpher_2,dis,csk,105240.0,906891.0,9/40,0.225000,0.021380,0.000046,0.121412,0.116045,0.000114,103.0
3,Molpher_3,dis,csk,89696.0,693460.0,20/37,0.540540,0.060264,0.000179,0.432727,0.129346,0.006726,4664.0
4,Molpher_4,dis,csk,81634.0,532962.0,34/43,0.790698,0.096859,0.000451,0.856230,0.153170,0.011708,6240.0
5,Molpher_mean,dis,csk,100068.0,823977.8,-,0.516682,0.053819,0.000158,0.360385,0.124815,0.004589,3041.2

In [ ]:
df_gen['KL_OS_IS'] = ['

In [20]:
df_KL_dis_0 = pd.read_csv("data/KL_divergence/df_KL_dis_0")
df_KL_dis_0

                 generator  KL_OS_IS  KL_OS_RS
0                  Molpher  0.404182  2.661215
1                 REINVENT  0.758605  2.952111
2                DrugEx_GT  0.377742  2.712360
3    DrugEx_GT_epsilon_0.1  0.756354  2.989940
4    DrugEx_GT_epsilon_0.6  0.405051  2.723309
5               DrugEx_RNN  0.568176  2.759121
6   DrugEx_RNN_epsilon_0.1  0.703502  2.879325
7   DrugEx_RNN_epsilon_0.6  0.518094  2.713713
8      DrugEx_epsilon_0.01  1.064774  3.556772
9       DrugEx_epsilon_0.1  0.832583  3.064448
10      DrugEx_epsilon_0.2  0.409366  2.658248
11      DrugEx_epsilon_0.4  0.370993  2.712992
12      DrugEx_epsilon_0.6  0.324838  2.678195