In [26]:
import pandas as pd
import numpy as np

In [27]:



for generator_name in ['Molpher', 'DrugEx_GT_epsilon_0.1','DrugEx_GT_epsilon_0.6']:
    for type_split in ['dis']:
        for type_scaffold in ['csk']:
            def_gen_1 = []
            def_gen_2 = []
            for x in [0,1,2,3,4]:    
                df_KL= pd.read_csv(f"data/results/Glucocorticoid_receptor/results_KL/df_KL_similarity_{type_scaffold}_{type_split}_{x}")
                def_gen_1.append(df_KL[df_KL.generator == generator_name][['KL_OS_IS']].values.flatten()[0])
                def_gen_2.append(df_KL[df_KL.generator == generator_name][['KL_OS_RS']].values.flatten()[0])
                
            a = np.mean(def_gen_1)
            b = np.mean(def_gen_2)
            
            def_gen_1.append(a)
            def_gen_2.append(b)
            
            
                
            df_gen = pd.read_csv(f"data/results/Glucocorticoid_receptor/{type_scaffold}_scaffolds/{type_split}/{generator_name}/df_all_clusters_with_mean.csv")
            df_gen['KL_OS_IS'] = def_gen_1
            df_gen['KL_OS_RS'] = def_gen_2
            
            mean = pd.DataFrame()
            mean = df_gen.loc[5].to_frame().T
            df_gen.to_csv(f"data/results/Glucocorticoid_receptor/{type_scaffold}_scaffolds/{type_split}/{generator_name}/df_all_clusters_with_KL_with_mean.csv", index=False)
            mean.to_csv(f"data/results/Glucocorticoid_receptor/{type_scaffold}_scaffolds/{type_split}/{generator_name}_mean_with_KL_{type_scaffold}_{type_split}.csv", index=False) #float_format='%.7f'

In [28]:
mean

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,TUPOR_unique,TUPOR_1,TUPOR_2,SESY,ASER,CwASo,metric_1,metric_2,KL_OS_IS,KL_OS_RS
5,DrugEx_GT_epsilon_0.6_mean,dis,csk,267648.0,907474.4,-,0.679649,0.025317,0.000147,1.055034,0.294816,0.007886,7186.4,0.000092,0.007986,0.000751,0.025066

In [29]:
df_gen = pd.read_csv("data/results/Glucocorticoid_receptor/csk_scaffolds/dis/Molpher/df_all_clusters_with_mean.csv")
df_gen

,name,type_cluster,scaffold,USo,SSo,TUPOR_,TUPOR,TUPOR_unique,TUPOR_1,TUPOR_2,SESY,ASER,CwASo,metric_1,metric_2
0,Molpher_0,dis,csk,104715.0,916546.0,15/40,0.375000,0.035812,0.000074,0.192796,0.114250,0.003291,3016.0,0.000143,0.003302
1,Molpher_1,dis,csk,119055.0,1070030.0,15/23,0.652174,0.054779,0.000038,0.198760,0.111263,0.001106,1183.0,0.000126,0.001107
2,Molpher_2,dis,csk,105240.0,906891.0,9/40,0.225000,0.021380,0.000046,0.121412,0.116045,0.000114,103.0,0.000086,0.000114
3,Molpher_3,dis,csk,89696.0,693460.0,20/37,0.540540,0.060264,0.000179,0.432727,0.129346,0.006726,4664.0,0.000223,0.006771
4,Molpher_4,dis,csk,81634.0,532962.0,34/43,0.790698,0.096859,0.000451,0.856230,0.153170,0.011708,6240.0,0.000417,0.011847
5,Molpher_mean,dis,csk,100068.0,823977.8,-,0.516682,0.053819,0.000158,0.360385,0.124815,0.004589,3041.2,0.000199,0.004628

In [ ]:
df_gen['KL_OS_IS'] = ['

In [20]:
df_KL_dis_0 = pd.read_csv("data/KL_divergence/df_KL_dis_0")
df_KL_dis_0

                 generator  KL_OS_IS  KL_OS_RS
0                  Molpher  0.404182  2.661215
1                 REINVENT  0.758605  2.952111
2                DrugEx_GT  0.377742  2.712360
3    DrugEx_GT_epsilon_0.1  0.756354  2.989940
4    DrugEx_GT_epsilon_0.6  0.405051  2.723309
5               DrugEx_RNN  0.568176  2.759121
6   DrugEx_RNN_epsilon_0.1  0.703502  2.879325
7   DrugEx_RNN_epsilon_0.6  0.518094  2.713713
8      DrugEx_epsilon_0.01  1.064774  3.556772
9       DrugEx_epsilon_0.1  0.832583  3.064448
10      DrugEx_epsilon_0.2  0.409366  2.658248
11      DrugEx_epsilon_0.4  0.370993  2.712992
12      DrugEx_epsilon_0.6  0.324838  2.678195

In [42]:
def connect_mean_value(reeptor, scaffold_type, type_cluster, generators_name_list):
    path = f"data/results/{receptor}/{scaffold_type}_scaffolds/{type_cluster}/"
    link = {}
    for generator in generators_name_list:
        link[f'link_{generator}'] = f'{path}{generator}_mean_with_KL_{scaffold_type}_{type_cluster}.csv'

    df = pd.DataFrame()
    for x,y in link.items():
        a = pd.read_csv(y)
        df = pd.concat([df, a], ignore_index=True)

    df = df.drop(columns = ['TUPOR_'])

    dff = df.copy()
    dff['SSo'] = dff['SSo'].apply(lambda x : "{:,}".format(x))
    dff['USo'] = dff['USo'].apply(lambda x : "{:,}".format(x))
    dff['CwASo'] = dff['CwASo'].apply(lambda x : "{:,}".format(x))

    
    dff.to_csv(f"{path}/mean_with_KL_{scaffold_type}_{type_cluster}_with_coma.csv", index = False)
    df.to_csv(f"{path}/mean_with_KL_{scaffold_type}_{type_cluster}.csv", index = False)
    dff.to_html(f"{path}/mean_with_KL_{scaffold_type}_{type_cluster}.html", index = False)

    
    display(df[['name','type_cluster','scaffold','USo',	'SSo','TUPOR', 'TUPOR_2', 'SESY','ASER','CwASo',	'metric_1',	'metric_2',	'KL_OS_IS']])
    return df

In [43]:
#type_cluster = 'dis' #options: 'dis'|'sim' 
#scaffold_type = 'csk' #options: 'csk'|'murcko'
#generators_name_list = [ 'Molpher', 'REINVENT'] #options: 'Molpher'|'DrugEx'
receptor = 'Glucocorticoid_receptor' #options: 'Glucocorticoid_receptor'|'Leukocyte_elastase'

generators_name_list= ['Molpher', 'DrugEx_GT_epsilon_0.1','DrugEx_GT_epsilon_0.6']
for type_cluster in ['dis']:
    for scaffold_type in ['csk']:
        df = connect_mean_value(receptor, scaffold_type, type_cluster, generators_name_list)

,name,type_cluster,scaffold,USo,SSo,TUPOR,TUPOR_2,SESY,ASER,CwASo,metric_1,metric_2,KL_OS_IS
0,Molpher_mean,dis,csk,100068.0,823977.8,0.516682,0.360385,0.124815,0.004589,3041.2,0.000199,0.004628,0.001139
1,DrugEx_GT_epsilon_0.1_mean,dis,csk,140428.0,809233.2,0.545466,0.511284,0.172969,0.004915,4063.2,0.000137,0.004957,0.002958
2,DrugEx_GT_epsilon_0.6_mean,dis,csk,267648.0,907474.4,0.679649,1.055034,0.294816,0.007886,7186.4,0.000092,0.007986,0.000751